stochasticai/xTuring

- README.md
- pyproject.toml
For transformers and peft library in README.md
> docs: add source installation information

- CONTRIBUTING.md
Updated information about pull requests
> fix: info about pr update

- CONTRIBUTING.md
> fix: contribution guide

- MANIFEST.in
- pyproject.toml
> build: release 0.0.3

- README.md
added documentation link to README.md
> docs: add docs link

- README.md
Changed Cerebras to Cerebras-GPT and other such changes in README.md
> docs: change readme to reflect new models

- README.md
- examples/bloom/bloom_lora.py
- examples/bloom/bloom_lora_int8.py
- src/xturing/config/finetuning_config.yaml
- src/xturing/config/generation_config.yaml
- src/xturing/engines/__init__.py
- src/xturing/engines/bloom_engine.py
- src/xturing/models/__init__.py
- src/xturing/models/bloom.py
- src/xturing/models/causal.py
- Fix genetaion method.
- Add bloom model
> fix: fix generation method

- src/xturing/config/__init__.py
- src/xturing/models/bloom.py
- src/xturing/models/causal.py
- src/xturing/models/cerebras.py
- src/xturing/models/galactica.py
- src/xturing/models/gpt2.py
- src/xturing/models/gptj.py
- src/xturing/models/llama.py
- src/xturing/models/opt.py
> feat: int8 gpu assert

- src/xturing/model_apis/openai.py
> feat: chat-gpt engine

- README.md
- examples/dataset_generation/create_instruction_dataset_from_files.ipynb
- src/xturing/datasets/instruction_dataset.py
- src/xturing/self_instruct/prepare_seed_tasks.py
add try catch to handle failed cases
> fix: data generation

- pyproject.toml
- src/xturing/engines/bloom_engine.py
- src/xturing/engines/causal.py
- src/xturing/engines/cerebras_engine.py
- src/xturing/engines/distilgpt2_engine.py
- src/xturing/engines/galactica_engine.py
- src/xturing/engines/gpt2_engine.py
- src/xturing/engines/gptj_engine.py
- src/xturing/engines/llama_engine.py
- src/xturing/engines/lora_engine/__init__.py
- src/xturing/engines/lora_engine/lora.py
- src/xturing/engines/opt_engine.py
- src/xturing/trainers/lightning_trainer.py
- Replace Peft and re-implement LoRA.
> feat: LoRA

- README.md
- examples/int4_finetuning/README.md
Changed README.md both for main and INT4 example
> docs: refined readme changes for INT4

- pyproject.toml
- src/xturing/engines/gptj_engine.py
- Fix GPT-J engine
- Add accelerate dependency
> fix: gpt-j engine, add dependency

- pyproject.toml
- src/xturing/engines/causal.py
- src/xturing/engines/gptj_utils/gptj.py
- src/xturing/utils/hub.py
- tests/xturing/models/test_gpt2_model.py
New transformers version, fixed issues with hub and added int8 lora test
> feat: transformers version, hub and tests

- CONTRIBUTING.md
- README.md
Updated README.md and CONTRIBUTING.md to reflect correct casing
> docs: fix xTuring casing

- .gitlint
- examples/falcon/falcon_lora_int8.py
- src/xturing/config/finetuning_config.yaml
- src/xturing/config/generation_config.yaml
- src/xturing/engines/__init__.py
- src/xturing/engines/causal.py
- src/xturing/engines/falcon_engine.py
- src/xturing/models/__init__.py
- src/xturing/models/falcon.py
Added falcon engines and models for falcon-7B from HuggingFace. Added example code in examples/ repo.
Refer below for the input prompt and the subsequent output from the falcon model (same for both base and with LoRA).
**Input**: Why LLM models are becoming so important?
**Output**: nThe LLM degree is a postgraduate law degree that is designed to provide students with a deeper understanding of the law. It is a popular choice for students who want to pursue a career in law, but it is also a good option for those who want to study law but do not have the time or money to attend a traditional law school.\nThe LLM degree is a postgraduate law degree that is designed to provide students with a deeper understanding of the law. It is a popular choice for students who want to pursue a career in …
> feat: added falcon model functionality

- .gitlint
- docs/docs/contributing/model_contributing.md
Added some missing steps and more reference for ease of contribution
> docs: Updating contribution guide

- src/xturing/utils/utils.py
Updated arguments clearing function
> feat: update of utils function

- README.md
Rectified the typos and converted the paragraph to bullets in README.md
> docs: Making changes suggested by Glenn

- src/xturing/models/causal.py
- src/xturing/models/generic.py
There was a bug in loading GenericLoraKbitModel, fixed that
> fix: fixed bug in loading kbit model

- docs/docs/advanced/api_server.md
A very minor fix, there was a typo in heading of api_server.md file
> fixed a minor typo in heading

- .github/workflows/semgrep.yml
Update Semgrep workflow to use Ubuntu 24.04
> ci: update Semgrep workflow to use Ubuntu 24.04
